### PR TITLE
Translator GUI project added by MihirRajeshPanchal

### LINKED ISSUE #34: Add a language translator GUI project.

### PR DESCRIPTION
**Pull request by MihirRajeshPanchal**
## 🛠️ Fixes Issue

 Closes #34 

## 👨‍💻 Changes proposed

Translator GUI project added by MihirRajeshPanchal

## Programming Languages and Technologies Used

Python

## ✔️ Check List (Check all the applicable boxes) 

- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project. 
- [x] This PR does not contain plagiarized content.
- [x] My Project has a README.md file with setup installation and screenshots
- [x] My Code is optimized to require less space by cleaning cached data

## 📄 Note to reviewers

Clueless Community Profile : https://www.clueless.tech/profile/admin/105093933941494861305

### CODE REVIEW

**Comment by MihirRajeshPanchal** [comment]
@nikhil25803 please review the PR I have added the requirements.txt file and the readme file for the same too

**Comment by MihirRajeshPanchal** [comment]
@nikhil25803 
https://www.clueless.tech/profile/admin/105093933941494861305

**Comment by MihirRajeshPanchal** [comment]
@nikhil25803 I think the points for this pull request are not yet updated with the leaderboard. Please do the needful 🙂

**Comment by nikhil25803** [comment]
@MihirRajeshPanchal | Leaderboard will be updated today evening.

**Pull request merged**
